import type { GenealogyResponse } from './types';

export const MOCK_GENEALOGY: GenealogyResponse = {
  focus: {
    id: 'MIXC-20260430-A01-03',
    uuid: 'uuid-focus',
    kind: 'focus',
    material_name: 'Mixed cathode slurry',
    status: 'InProgress',
    risk: 'high',
    reason: 'Failed coating QC — primary investigation target',
    recommended_action: 'View full QC failure report',
    tier: 0,
  },
  ancestors: [
    {
      id: 'FOIL-20260428-AL-02',
      uuid: 'uuid-raw1',
      kind: 'input_material',
      material_name: 'Aluminum foil substrate',
      supplier: 'Targray Industries',
      status: 'OnHold',
      risk: 'medium',
      reason: 'Shared substrate foil lot used in failed sub-batch',
      recommended_action: 'Flag supplier lot FOIL-20260428-AL-02',
      tier: -2,
    },
    {
      id: 'NMC-20260428-LOT3',
      uuid: 'uuid-raw2',
      kind: 'input_material',
      material_name: 'NMC811 cathode active',
      supplier: 'Umicore',
      status: 'Released',
      risk: 'none',
      reason: 'Not implicated — clean QC trail on this lot',
      tier: -2,
    },
    {
      id: 'BINDER-20260427-PV-01',
      uuid: 'uuid-raw3',
      kind: 'input_material',
      material_name: 'PVDF binder',
      supplier: 'Kureha Corp',
      status: 'Released',
      risk: 'none',
      reason: 'Not implicated — clean QC trail on this lot',
      tier: -2,
    },
    {
      id: 'MIXC-20260430-A01',
      uuid: 'uuid-parent',
      kind: 'parent_batch',
      material_name: 'Mixed cathode slurry',
      status: 'InProgress',
      risk: 'medium',
      reason: 'Parent of the failed sub-batch — under review',
      recommended_action: 'Place parent batch on hold pending sub-batch clearance',
      tier: -1,
    },
  ],
  descendants: [
    {
      id: 'MIXC-20260430-A01-01',
      uuid: 'uuid-sib1',
      kind: 'sibling_sub_batch',
      material_name: 'Mixed cathode slurry',
      status: 'Released',
      risk: 'low',
      reason: 'Same parent, earlier run · passed all QC checks',
      recommended_action: 'Hold pending re-inspection',
      tier: 1,
    },
    {
      id: 'MIXC-20260430-A01-02',
      uuid: 'uuid-sib2',
      kind: 'sibling_sub_batch',
      material_name: 'Mixed cathode slurry',
      status: 'Released',
      risk: 'low',
      reason: 'Same parent, earlier run · passed all QC checks',
      recommended_action: 'Hold pending re-inspection',
      tier: 1,
    },
  ],
  edges: [
    { from_uuid: 'uuid-raw1', to_uuid: 'uuid-parent', highlighted: true },
    { from_uuid: 'uuid-raw2', to_uuid: 'uuid-parent', highlighted: false },
    { from_uuid: 'uuid-raw3', to_uuid: 'uuid-parent', highlighted: false },
    { from_uuid: 'uuid-parent', to_uuid: 'uuid-focus', highlighted: true },
    { from_uuid: 'uuid-focus', to_uuid: 'uuid-sib1', highlighted: false },
    { from_uuid: 'uuid-focus', to_uuid: 'uuid-sib2', highlighted: false },
  ],
};
